// Generated by CoffeeScript 1.3.3
var app, auth, config, express, io, path, routes, server;

routes = require("./routes");

config = require("./config");

express = require("express");

path = require("path");

app = express();

server = require("http").Server(app);

io = require("socket.io").listen(server);

app.configure(function() {
  app.set("port", process.env.PORT || 3000);
  app.set("views", __dirname + "/views");
  app.set("view engine", "jade");
  app.set("title", config.title);
  app.use(express.favicon());
  app.use(express.logger("dev"));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  app.use(require("stylus").middleware(__dirname + "/public"));
  return app.use(express["static"](path.join(__dirname, "public")));
});

app.configure("development", function() {
  return app.use(express.errorHandler());
});

app.get("/", routes.slides);

auth = express.basicAuth(config.username, config.password);

app.get("/rc", auth, routes.rc);

server.listen(app.get("port"), function() {
  return console.log("Express server listening on port " + app.get("port"));
});

io.on("connection", function(socket) {
  socket.on("next", function(data) {
    return socket.broadcast.emit("next", data);
  });
  socket.on("prev", function(data) {
    return socket.broadcast.emit("prev", data);
  });
  socket.on("slide", function(data) {
    return socket.broadcast.emit("slide", data);
  });
  return socket.on("index", function(data) {
    return socket.broadcast.emit("index", data);
  });
});
